on: push

name: Integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - name: build  
        run: |
          go build
      - name : run tests          
        run : |
            go test

  docker-build : 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: build
        run: |  
          docker build .

        

